name: 'Setup VS Dev Environment'
description: 'Sets VS dev environment variables and PATH via devenv (like vcvarsall) for using msbuild, cl.exe, link.exe, etc.'
branding:
  icon: 'code'
  color: 'purple'
inputs:
  vswhere:
    description: 'Name or path to vswhere.exr'
    default: 'vswhere.exe'
  arch:
    description: 'Target build architecture'
    default: 'amd64'
  host_arch:
    description: 'Host architecture (x86, x86_amd64, or amd64)'
    default: ''
  winsdk:
    description: 'Overrides the default WinSDK version'
    default: ''
  toolset_version:
    description: 'Overrides the default toolset version'
    default: ''
  components:
    description: 'List of components required in the selected VS installation (semi-colon separated)'
    default: 'Microsoft.VisualStudio.Component.VC.Tools.x86.x64'
outputs:
  install_path:
    description: 'VS installation path'
runs:
  using: 'node16'
  main: 'dist/index.js'
